OUT = main4
SRC = main4.cpp
CC = g++
CFLAGS = -o
IFLAGS = -I/home/pi/libusbp/include
LFLAGS = -L/home/pi/libusbp/build
LIBS = -lusb-1.0
LIBS = -lusbp-1

$(OUT): $(SRC)
	$(CC) $(CFLAGS) $(OUT) $(IFLAGS) $(LFLAGS) $(LIBS) $(SRC)
